name: openwrt-25.12-gcc15-Public

on: workflow_dispatch

permissions:
  contents: write

jobs:
  build:
    name: ${{ matrix.model }}-${{ matrix.libc }}-${{ matrix.tools }}
    runs-on: ubuntu-24.04

    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        model:
          - x86_64
          # - nanopi-r5s
          # - netgear_r8500
          # - redmi_ax6000
        tag:
          - type: rc2
            version: openwrt-25.12
        libc:
          - musl
        tools:
          - ccache
          - noccache

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: Show system
      run: |
        lscpu
        free -h
        df -Th
        uname -a
    - name: Set release env
      run: |
        sudo mkdir -p /builder
        sudo chown -R runner.runner /builder
        echo 'WORKDIR=/builder' >> "$GITHUB_ENV"
        git config --global user.name 'actions'
        git config --global user.email 'action@github.com'
    - name: Free disk space
      uses: sbwml/actions@free-disk
      with:
        build-mount-path: /builder

    - name: Build System Setup
      uses: sbwml/actions@openwrt-build-setup

    - name: Install LLVM
      uses: sbwml/actions@install-llvm

    - name: Compile OpenWrt
      working-directory: /builder
      env:
        git_name: grandway2025
        git_password: ${{ secrets.GH_TOKEN }}
      run: |
        set -e
        [ "${{ matrix.libc }}" = "glibc" ] && export ENABLE_GLIBC=y
        [ "${{ matrix.tools }}" = "ccache" ] && export ENABLE_CCACHE=y
        BUILD_SH_URL="https://raw.githubusercontent.com/grandway2025/Build/main/openwrt/build.sh"
        curl -fsSL "$BUILD_SH_URL" -o build.sh
        chmod +x build.sh
        bash -n build.sh
        BUILD_TOOLCHAIN=y \
        ENABLE_LTO=y \
        ENABLE_BPF=y \
        USE_GCC15=y \
        ENABLE_MOLD=y \
        VERSION=main \
        bash ./build.sh ${{ matrix.tag.type }} ${{ matrix.model }}
        
    - name: Create release
      uses: ncipollo/release-action@v1.14.0
      with:
        name: ${{ matrix.tag.version }}
        allowUpdates: true
        tag: ${{ matrix.tag.version }}
        commit: openwrt-25.12
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ${{ env.WORKDIR }}/openwrt/toolchain-cache/*
